#' Make markdown files for talks
#'
#' This function will create markdown files in the Hugo Apero style for talks
#' specified in a Google Sheet.
#'
#' @param id Your Google Sheet id
#' @export
make_talk_md <- function(id = "1-PItelqpv0Sb_LdiEDqb8O3D_Roii5nVTL07IRVbRtA") {
  d <- googlesheets4::range_read(googlesheets4::as_sheets_id(id))
  d <- d[d$manual == 0, ]
  md <- glue::glue_data(d, {
    "---
## Generated by the R package lazyapero
## Do not edit directly, edit the Google Sheet [id = <id>]
title: \"<title>\"
author: \"<who>\"
event: \"<where>\"
date: <start>
date_end: <end>
categories:
 - <ifelse(invited == 1, 'invited', 'contributed')>
 - <what>
excerpt: \"<abstract>\"
links:
- icon: images
  icon_pack: fas
  name: slides
  url: <link>
---
"
  }, .open = "<", .close = ">")
  dir <- tolower(gsub(" ", "_", d$where))
  purrr::map(dir, function(x) {
    if (!dir.exists(glue::glue("content/talk/{x}"))) {
      dir.create(glue::glue("content/talk/{x}"))
    }
  })
  file_name <- glue::glue("content/talk/{dir}/index.md")
  purrr::walk2(md, file_name, writeLines)
}
