#' Make markdown files for workshops
#'
#' This function will create markdown files in the Hugo Apero style for talks
#' specified in a Google Sheet after filtering (in this case to workshops).
#'
#' @param id Your Google Sheet id
#' @param filter_column column to filter sheet by
#' @param filter_term term to filter column specified in `filter_column`
#' @export
upload_workshop_md <- function(id = "1-PItelqpv0Sb_LdiEDqb8O3D_Roii5nVTL07IRVbRtA",
                           filter_column = "what", filter_term = "Workshop") {
  o <- make_workshop_md(id = id, filter_column = filter_column, filter_term = filter_term)
  md <- o$md
  d <- o$d
  dir <- tolower(gsub("[/]", "", gsub(" ", "_", d$where)))
  dir <- make.unique(dir, sep = "_")
  purrr::map(dir, function(x) {
    if (!dir.exists(glue::glue("content/workshops/{x}"))) {
      dir.create(glue::glue("content/workshops/{x}"))
      print(glue::glue("Creating folder 'content/workshops/{x}'"))
    }
  })
  file_name <- glue::glue("content/workshops/{dir}/index.md")
  purrr::walk2(md, file_name, writeLines)
}

make_workshop_md <- function(id = "1-PItelqpv0Sb_LdiEDqb8O3D_Roii5nVTL07IRVbRtA",
                             filter_column, filter_term) {
  d <- googlesheets4::range_read(googlesheets4::as_sheets_id(id))
  d <- d[d[[filter_column]] == filter_term, ]
  d <- d[d$manual == 0, ]
  md <- glue::glue_data(d, {
    "---
## Generated by the R package lazyapero
## Do not edit directly, edit the Google Sheet [id = <id>]
title: \"<title>\"
author: \"<who>\"
event: \"<where>\"
date: <start>
date_end: <end>
categories:
 - <ifelse(invited == 1, 'Invited', 'Contributed')>
 - <what>
excerpt: \"<fix_quote(abstract)>\"
links:
<ifelse(!is.na(details), glue::glue('\\n- icon: link\\n  icon_pack: fas\\n  name: Register\\n  url: {details}'), '')>
<ifelse(!is.na(slides), glue::glue('\\n- icon: images\\n  icon_pack: fas\\n  name: slides\\n  url: {slides}'), '')>
<ifelse(!is.na(video), glue::glue('\\n- icon: video\\n  icon_pack: fas\\n  name: video\\n  url: {video}'), '')>
<ifelse(!is.na(poster), glue::glue('\\n- icon: sticky-note\\n  icon_pack: fas\\n  name: poster\\n  url: {poster}'), '')>
<ifelse(!is.na(pdf), glue::glue('\\n- icon: file\\n  icon_pack: fas\\n  name: pdf\\n  url: {pdf}'), '')>

---
"
  }, .open = "<", .close = ">")
  list(md = md, d = d)
}

fix_quote <- function(x) {
  gsub('"', '\\\\"', x)
}
