#' Make markdown files for papers
#'
#' This function will create markdown files in the Hugo Apero style for papers
#' specified in a Google Sheet.
#'
#' @param id Your Google Sheet id
#' @export
upload_paper_md <- function(id = "1HPQDH3tOXtZb1DV--8wR9CKAzUz5aywWc2vM3OQ5SrU") {
  o <- make_paper_md(id = id)
  md <- o$md
  d <- o$d
  dir <- glue::glue('{d$year}_{tolower(gsub(" ", "_", substr(d$title, 1, 20)))}')
  purrr::map(dir, function(x) {
    if (!dir.exists(glue::glue("content/writing/{x}"))) {
      dir.create(glue::glue("content/writing/{x}"))
      print(glue::glue("Creating folder 'content/writing/{x}'"))
    }
  })
  file_name <- glue::glue("content/writing/{dir}/index.md")
  purrr::walk2(md, file_name, writeLines)
}

make_paper_md <- function(id = "1HPQDH3tOXtZb1DV--8wR9CKAzUz5aywWc2vM3OQ5SrU") {
  d <- googlesheets4::range_read(googlesheets4::as_sheets_id(id))
  d <- d[d$type == "article" | (d$type == "press" & d$description %in% c("article", "op-ed")) | d$type == "blog", ]
  d$year <- as.numeric(d$year)
  md <- glue::glue_data(d, {
    "---
## Generated by the R package lazyapero
## Do not edit directly, edit the Google Sheet [id = <id>]
title: \"<title>\"
author: \"<authors>\"
date: <date>
link_out: <ifelse(pub_type %in% c(2, 3, 4, 5, 6, 7), 'false', 'true')>
i: <link>
categories:
 - <ifelse(pub_type == 2, 'Peer Reviewed Article',
    ifelse(pub_type == 3, 'Editorial/Reply',
    ifelse(pub_type == 4, 'Review',
    ifelse(pub_type == 5, 'Book',
    ifelse(pub_type == 6, 'Book section',
    ifelse(pub_type == 7, 'Thesis',
    ifelse(pub_type == 8, 'Op-ed',
    ifelse(pub_type == 9, 'Blog post', ''))))))))>
links:
<ifelse(!is.na(url_source), glue::glue('\\n- icon: link\\n  icon_pack: fas\\n  name: link\\n  url: {url_source}'), '')>
<ifelse(!is.na(link), glue::glue('\\n- icon: link\\n  icon_pack: fas\\n  name: link\\n  url: {link}'), '')>
<ifelse(!is.na(url_pdf), glue::glue('\\n- icon: file\\n  icon_pack: fas\\n  name: pdf\\n  url: {url_pdf}'), '')>

---

<fix_quote(ifelse(is.na(abstract), '', abstract))>

"
  }, .open = "<", .close = ">")
  list(md = md, d = d)
}

fix_quote <- function(x) {
  gsub('"', '\\\\"', x)
}
