#' Make markdown files for talks
#'
#' This function will create markdown files in the Hugo Apero style for talks
#' specified in a Google Sheet.
#'
#' @param id Your Google Sheet id
#' @export
upload_talk_md <- function(id = "1-PItelqpv0Sb_LdiEDqb8O3D_Roii5nVTL07IRVbRtA") {
  o <- make_talk_md(id = id)
  md <- o$md
  d <- o$d
  dir <- tolower(gsub(" ", "_", d$where))
  purrr::map(dir, function(x) {
    if (!dir.exists(glue::glue("content/talk/{x}"))) {
      dir.create(glue::glue("content/talk/{x}"))
      print(glue::glue("Creating folder 'content/talk/{x}'"))
    }
  })
  file_name <- glue::glue("content/talk/{dir}/index.md")
  purrr::walk2(md, file_name, writeLines)
}

make_talk_md <- function(id = "1-PItelqpv0Sb_LdiEDqb8O3D_Roii5nVTL07IRVbRtA") {
  d <- googlesheets4::range_read(googlesheets4::as_sheets_id(id))
  d <- d[d$manual == 0, ]
  md <- glue::glue_data(d, {
    "---
## Generated by the R package lazyapero
## Do not edit directly, edit the Google Sheet [id = <id>]
title: \"<title>\"
author: \"<who>\"
event: \"<where>\"
date: <start>
date_end: <end>
categories:
 - <ifelse(invited == 1, 'Invited', 'Contributed')>
 - <what>
excerpt: \"<abstract>\"
links:
<ifelse(!is.na(slides), glue::glue('\\n- icon: images\\n  icon_pack: fas\\n  name: slides\\n  url: {slides}'), '')>
<ifelse(!is.na(video), glue::glue('\\n- icon: images\\n  icon_pack: fas\\n  name: video\\n  url: {video}'), '')>
<ifelse(!is.na(poster), glue::glue('\\n- icon: images\\n  icon_pack: fas\\n  name: sticky-note\\n  url: {poster}'), '')>
<ifelse(!is.na(details), glue::glue('\\n- icon: images\\n  icon_pack: fas\\n  name: link\\n  url: {details}'), '')>
<ifelse(!is.na(pdf), glue::glue('\\n- icon: images\\n  icon_pack: fas\\n  name: file\\n  url: {pdf}'), '')>

---
"
  }, .open = "<", .close = ">")
  list(md = md, d = d)
}
