#' Make markdown files for media
#'
#' This function will create markdown files in the Hugo Apero style for media
#' specified in a Google Sheet.
#'
#' @param id Your Google Sheet id
#' @export
upload_media_md <- function(id = "1HPQDH3tOXtZb1DV--8wR9CKAzUz5aywWc2vM3OQ5SrU") {
  md <- make_media_md(id = id)
  writeLines(md, "content/media/main/index.md")
}

make_media_md <- function(id = "1HPQDH3tOXtZb1DV--8wR9CKAzUz5aywWc2vM3OQ5SrU") {
  d <- googlesheets4::range_read(googlesheets4::as_sheets_id(id))
  d <- d[d$type == "press", ]
  d$year <- as.numeric(d$year)
  d <- d[order(-d$year), ]
  md <- glue::glue({
    '
{ifelse(d$description == "podcast", "<i class=\'fas fa-microphone-alt\'></i>",
 ifelse(d$description == "write-up", "<i class=\'fas fa-newspaper\'></i>",
 ifelse(d$description == "op-ed", "<i class=\'fas fa-pen-alt\'></i>",
 ifelse(d$description == "quoted", "<i class=\'fas fa-quote-left\'></i>",
 ifelse(d$description == "televised interview", "<i class=\'fas fa-tv\'></i>",
 ifelse(d$description == "radio", "<i class=\'fas fa-headphones\'></i>", ""))))))} [{fix_quote(d$title)}]({d$link}) in {d$publication} [{d$year}] *{d$description}* </br></br>

'
  })
  glue::glue("---
## Generated by the R package lazyapero
## Do not edit directly, edit the Google Sheet [id = <id>]
intro: \"{glue::glue_collapse(md)}\"
---")
}

